# Reinforcement Learning

Reinforcement learning (RL) is the subfield of machine learning concerned with decision making and motor control. It studies how an agent can learn how to achieve goals in a complex, uncertain environment. It’s exciting for two reasons:

RL is very general, encompassing all problems that involve making a sequence of decisions: for example, controlling a robot’s motors so that it’s able to run and jump, making business decisions like pricing and inventory management, or playing video games and board games. RL can even be applied to supervised learning problems with sequential or structured outputs.
RL algorithms have started to achieve good results in many difficult environments. RL has a long history, but until recent advances in deep learning, it required lots of problem-specific engineering. DeepMind’s Atari results, BRETT from Pieter Abbeel’s group, and AlphaGo all used deep RL algorithms which did not make too many assumptions about their environment, and thus can be applied in other settings.

In [7]:
import sys
sys.version

'3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)]'

In [8]:
import gym
print(gym.__version__)

import keras
print(keras.__version__)


0.10.9


C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


2.2.4


# Setting up OpenAI gym Environment

In [17]:
import gym
env = gym.make('CartPole-v0')
env.reset()
for _ in range(1000):
    env.render()
    env.step(env.action_space.sample()) # take a random action

E:\Work\Machine Learning\OpenAI\gym\gym\logger.py:30: UserWarning: WARN: You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))


The environment’s step function returns exactly what we need. In fact, step returns four values. These are:

observation (object): an environment-specific object representing your observation of the environment. For example, pixel data from a camera, joint angles and joint velocities of a robot, or the board state in a board game.

reward (float): amount of reward achieved by the previous action. The scale varies between environments, but the goal is always to increase your total reward.

done (boolean): whether it’s time to reset the environment again. Most (but not all) tasks are divided up into well-defined episodes, and done being True indicates the episode has terminated. (For example, perhaps the pole tipped too far, or you lost your last life.)

info (dict): diagnostic information useful for debugging. It can sometimes be useful for learning (for example, it might contain the raw probabilities behind the environment’s last state change). However, official evaluations of your agent are not allowed to use this for learning.

In [2]:
import gym
env = gym.make('CartPole-v0')
for i_episode in range(20):
    observation = env.reset()
    for t in range(100):
        env.render()
        print(observation)
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break

[-0.02627873  0.01616331 -0.01286257 -0.0408965 ]
[-0.02595547 -0.17877185 -0.0136805   0.24770057]
[-0.02953091  0.01654278 -0.00872649 -0.0492659 ]
[-0.02920005  0.21178877 -0.00971181 -0.34468929]
[-0.02496427  0.01680631 -0.0166056  -0.05508462]
[-0.02462815  0.21216238 -0.01770729 -0.35296014]
[-0.0203849   0.40753159 -0.02476649 -0.65117369]
[-0.01223427  0.60298957 -0.03778996 -0.95155135]
[-1.74477831e-04  7.98599160e-01 -5.68209916e-02 -1.25586386e+00]
[ 0.01579751  0.99440066 -0.08193827 -1.5657885 ]
[ 0.03568552  1.19040064 -0.11325404 -1.88286497]
[ 0.05949353  1.38655877 -0.15091134 -2.20844273]
[ 0.08722471  1.19317287 -0.19508019 -1.96586049]
Episode finished after 13 timesteps
[ 0.02349001 -0.02628948 -0.000688    0.02391997]
[ 2.29642188e-02  1.68842326e-01 -2.09600214e-04 -2.68979945e-01]
[ 0.02634107 -0.02627663 -0.0055892   0.02363687]
[ 0.02581553 -0.22131799 -0.00511646  0.31455111]
[ 0.02138917 -0.41636668  0.00117456  0.60561609]
[ 0.01306184 -0.61150504  0.0132

[0.00936282 0.00425665 0.11549843 0.36455941]
[ 0.00944795 -0.19230108  0.12278961  0.69131273]
[0.00560193 0.00092254 0.13661587 0.43966901]
[0.00562038 0.19387333 0.14540925 0.19297979]
[ 0.00949785 -0.00299703  0.14926885  0.52776871]
[0.00943791 0.18974435 0.15982422 0.28559379]
[ 0.0132328  -0.00725314  0.1655361   0.62411254]
[ 0.01308773 -0.20425197  0.17801835  0.96401703]
[ 0.00900269 -0.01191023  0.19729869  0.73212531]
Episode finished after 27 timesteps
[0.04373555 0.03673634 0.01370215 0.0059854 ]
[ 0.04447028  0.23165913  0.01382186 -0.28234303]
[ 0.04910346  0.42658123  0.008175   -0.57063476]
[ 0.05763508  0.62158759 -0.00323769 -0.8607311 ]
[ 0.07006683  0.81675348 -0.02045232 -1.15443029]
[ 0.0864019   0.62190414 -0.04354092 -0.86822996]
[ 0.09883999  0.42740079 -0.06090552 -0.58954844]
[ 0.107388    0.23318217 -0.07269649 -0.31665583]
[ 0.11205165  0.42926023 -0.07902961 -0.63135004]
[ 0.12063685  0.62539072 -0.09165661 -0.94783805]
[ 0.13314467  0.8216193  -0.110613

The Discrete space allows a fixed range of non-negative numbers, so in this case valid actions are either 0 or 1. The Box space represents an n-dimensional box, so valid observations will be an array of 4 numbers.

In [2]:
import gym
env = gym.make('CartPole-v0')
print(env.action_space)
print(env.observation_space)

Discrete(2)
Box(4,)


In [3]:
print(env.observation_space.high)
print(env.observation_space.low)

[4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38]


This introspection can be helpful to write generic code that works for many different environments. Box and Discrete are the most common Spaces. You can sample from a Space or check that something belongs to it:

In [5]:
from gym import spaces
space = spaces.Discrete(8) # Set with 8 elements {0, 1, 2, ..., 7}
x = space.sample()
assert space.contains(x)
assert space.n == 8

In [6]:
from gym import envs
print(envs.registry.all())

dict_values([EnvSpec(Copy-v0), EnvSpec(RepeatCopy-v0), EnvSpec(ReversedAddition-v0), EnvSpec(ReversedAddition3-v0), EnvSpec(DuplicatedInput-v0), EnvSpec(Reverse-v0), EnvSpec(CartPole-v0), EnvSpec(CartPole-v1), EnvSpec(MountainCar-v0), EnvSpec(MountainCarContinuous-v0), EnvSpec(Pendulum-v0), EnvSpec(Acrobot-v1), EnvSpec(LunarLander-v2), EnvSpec(LunarLanderContinuous-v2), EnvSpec(BipedalWalker-v2), EnvSpec(BipedalWalkerHardcore-v2), EnvSpec(CarRacing-v0), EnvSpec(Blackjack-v0), EnvSpec(KellyCoinflip-v0), EnvSpec(KellyCoinflipGeneralized-v0), EnvSpec(FrozenLake-v0), EnvSpec(FrozenLake8x8-v0), EnvSpec(CliffWalking-v0), EnvSpec(NChain-v0), EnvSpec(Roulette-v0), EnvSpec(Taxi-v2), EnvSpec(GuessingGame-v0), EnvSpec(HotterColder-v0), EnvSpec(Reacher-v2), EnvSpec(Pusher-v2), EnvSpec(Thrower-v2), EnvSpec(Striker-v2), EnvSpec(InvertedPendulum-v2), EnvSpec(InvertedDoublePendulum-v2), EnvSpec(HalfCheetah-v2), EnvSpec(Hopper-v2), EnvSpec(Swimmer-v2), EnvSpec(Walker2d-v2), EnvSpec(Ant-v2), EnvSpec(Hum